[project]
name = "periodica"
version = "v7.9.3-alpha"
description = "CLI tool for displaying element and isotope information"
requires-python = ">=3.11"
dependencies = ["requests", "packaging"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
